import type { Metadata } from "next";
import { Container , SSRProvider } from "@/components/bootstrap";
import NavBar from "./NavBar";
import "bootstrap/dist/css/bootstrap.min.css"; // 👈 Import this


export const metadata: Metadata = {
  title: "Nextjs Image Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SSRProvider>
          <NavBar />
          <main>
            <Container className="py-1">
              {children}
            </Container>
          </main>
        </SSRProvider>
      </body>
    </html>
  );
}
